version: '3.5'

services:

  nextcloud-frontend:
    hostname: 'nextcloud-frontend'
    container_name: 'nextcloud-frontend'
    build:
      context: './'
      dockerfile: '${PWD}/app/frontend/dockerfile'
    volumes:
      - 'nextcloud:/var/www/nextcloud/'
      - type: "bind"
        source: "${PWD}/app/frontend/rootfs/etc/nginx/nginx.conf"
        target: "/etc/nginx/nginx.conf"
    networks:
      - 'internal-nextcloud'
      - 'external'
    healthcheck:
      interval: '5s'
      retries: '15'
      timeout: '2s'
      test: 
        - "CMD"
        - "service" 
        - "nginx"
        - "status"
    ports:
      - '443:443'
      - '80:80'
      - '9001:9001'
    depends_on:
      - 'nextcloud-backend'

  nextcloud-database:
    hostname: 'nextcloud-database'
    container_name: 'nextcloud-database'
    image: 'mysql'
    volumes:
    - type: "bind"
      source: "${PWD}/app/database/rootfs/docker-entrypoint-initdb.d"
      target: "/docker-entrypoint-initdb.d/"
    networks:
      - 'internal-nextcloud'
    healthcheck:
      interval: '5s'
      retries: '15'
      timeout: '10s'
      test: 
      - "CMD"
      - "mysqladmin"
      - "-uroot"
      - "-plocal"
      - "ping"
      - "-h"
      - "localhost"
    environment:
      MYSQL_ROOT_PASSWORD: 'local'

  nextcloud-backend:
    hostname: 'nextcloud-backend'
    container_name: 'nextcloud-backend'
    build:
      context: './'
      dockerfile: '${PWD}/app/backend/dockerfile'
    volumes:
      - 'nextcloud:/var/www/html/'
    networks:
      - 'internal-nextcloud'
    depends_on:
      - 'nextcloud-database'
    environment:
      MYSQL_HOST: nextcloud-database
      MYSQL_USER: root
      MYSQL_PASSWORD: local
      MYSQL_DATABASE: nextcloud
      TRUSTED_PROXIES: nextcloud-frontend
      NEXTCLOUD_TRUSTED_DOMAINS: deb10-docker

networks:
  internal-nextcloud:
  external:

volumes:
  nextcloud:
    driver: 'local'
