version: '3.2'

services:

  keycloak-frontend:
    hostname: 'keycloak-frontend'
    container_name: 'keycloak-frontend'
    build:
      context: './'
      dockerfile: '${PWD}/app/frontend/dockerfile'
        #    volumes:
        #      - type: "bind"
        #        source: "${PWD}/app/frontend/rootfs/etc/nginx/nginx.conf"
        #        target: "/etc/nginx/nginx.conf"
    networks:
      - 'external'
      - 'internal-keycloak'
    healthcheck:
      interval: '5s'
      retries: '15'
      timeout: '2s'
      test: 
        - "CMD"
        - "service" 
        - "nginx"
        - "status"
    ports:
      - '443:443'
    depends_on:
      - 'keycloak-backend'

  keycloak-backend:
    hostname: 'keycloak-backend'
    container_name: 'keycloak-backend'
    build:
      context: './'
      dockerfile: '${PWD}/app/backend/dockerfile'
    networks:
      - 'internal-keycloak'
    healthcheck:
      interval: '5s'
      timeout: '2s'
      retries: '15'
      test: 
        - "CMD"
        - "curl -f"
        - "http://localhost:8080/keycloak/"
    depends_on:
      - 'keycloak-database'
    environment:
      KEYCLOAK_DATASOURCE_URL: 'jdbc:mysql://keycloak-database:3306/keycloak'
      KC_DB_USERNAME: 'root'
      KC_DB_PASSWORD: 'local'
      KC_HOSTNAME_HTTPS_STRICT: 'false'
      KC_HOSTNAME_STRICT: 'false'
      KC_LOG_LEVEL: 'info'
      KC_PROXY: 'edge'
      KC_HTTP_ENABLED: 'true'
      KC_HOST_NAME: '/keycloak'
      KEYCLOAK_ADMIN: 'root' 
      KEYCLOAK_ADMIN_PASSWORD: 'local'
      REDIRECT_SOCKET: 'proxy-https'
      PROXY_ADDRESS_FORWARDING: 'true'

  keycloak-database:
    hostname: 'keycloak-database'
    container_name: 'keycloak-database'
    image: 'mysql'
    volumes:
    - type: "bind"
      source: "${PWD}/app/database/rootfs/docker-entrypoint-initdb.d"
      target: "/docker-entrypoint-initdb.d/"
    networks:
      - 'internal-keycloak'
    healthcheck:
      interval: '5s'
      retries: '15'
      timeout: '10s'
      test: 
      - "CMD"
      - "mysqladmin"
      - "-uroot"
      - "-plocal"
      - "ping"
      - "-h"
      - "localhost"
    environment:
      MYSQL_ROOT_PASSWORD: 'local'

networks:
  external:
  internal-keycloak:

